"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
type Item={id?:string;description:string;unit:string;qty:number;unitPrice:number};
export default function EstimateEditor({orderId,estimate}:{orderId:string;estimate:any|null}){const router=useRouter();const [items,setItems]=useState<Item[]>(estimate?.items?.map((x:any)=>({...x,qty:Number(x.qty),unitPrice:Number(x.unitPrice)}))||[]);const [discount,setDiscount]=useState(Number(estimate?.discount||0));const [notes,setNotes]=useState(estimate?.notes||"");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const draft=estimate?.status==="DRAFT";const subtotal=items.reduce((s,x)=>s+Number(x.qty||0)*Number(x.unitPrice||0),0),total=Math.max(0,subtotal-discount);
 async function create(){setBusy(true);const r=await fetch('/api/estimates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId})});const d=await r.json();setMsg(r.ok?'تم إنشاء مقايسة Ventic Pro من مقايسة العميل':d.error||'تعذر الإنشاء');setBusy(false);if(r.ok)router.refresh()}
 async function save(){setBusy(true);const r=await fetch(`/api/estimates/${estimate.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,discount,notes})});const d=await r.json();setMsg(r.ok?'تم حفظ المقايسة':d.error||'تعذر الحفظ');setBusy(false);if(r.ok)router.refresh()}
 async function send(){setBusy(true);const r=await fetch(`/api/estimates/${estimate.id}/send`,{method:'POST'});const d=await r.json();if(r.ok){const url=`${location.origin}${d.approvalPath}`;await navigator.clipboard?.writeText(url);setMsg(`تم اعتمادها للإرسال. رابط العميل: ${url}`);router.refresh()}else setMsg(d.error||'تعذر الإرسال');setBusy(false)}
 if(!estimate)return <div className="adminQuick" style={{marginTop:24}}><h2>مقايسة Ventic Pro</h2><p>مقايسة العميل محفوظة كما قدمها. أنشئ مقايسة Ventic Pro مستقلة للتعديل والاعتماد والفاتورة.</p><button className="button" disabled={busy} onClick={create}>إنشاء مقايسة من طلب العميل</button>{msg&&<p>{msg}</p>}</div>;
 return <div className="adminQuick" style={{marginTop:24,display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><h2 style={{marginBottom:4}}>مقايسة Ventic Pro — إصدار {estimate.version}</h2><small>الحالة: {estimate.status}</small></div><b style={{fontSize:24}}>{total.toLocaleString('ar-EG')} ج</b></div>
 <div style={{overflowX:'auto',marginTop:16}}><table style={{width:'100%',minWidth:720}}><thead><tr><th>البند</th><th>الوحدة</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th><th></th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td><input disabled={!draft} value={x.description} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,description:e.target.value}:v))}/></td><td><input disabled={!draft} value={x.unit} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,unit:e.target.value}:v))}/></td><td><input disabled={!draft} type="number" step="0.01" value={x.qty} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,qty:Number(e.target.value)}:v))}/></td><td><input disabled={!draft} type="number" step="0.01" value={x.unitPrice} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,unitPrice:Number(e.target.value)}:v))}/></td><td>{(x.qty*x.unitPrice).toLocaleString('ar-EG')} ج</td><td>{draft&&<button className="ghostBtn" onClick={()=>setItems(a=>a.filter((_,j)=>j!==i))}>حذف</button>}</td></tr>)}</tbody></table></div>
 {draft&&<><button className="ghostBtn" style={{marginTop:12}} onClick={()=>setItems(a=>[...a,{description:'',unit:'وحدة',qty:1,unitPrice:0}])}>+ إضافة بند</button><div className="grid2" style={{marginTop:16}}><label className="field"><span>الخصم</span><input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><label className="field"><span>ملاحظات المقايسة</span><input value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="orderActions"><button className="ghostBtn" disabled={busy} onClick={save}>حفظ المسودة</button><button className="button" disabled={busy||items.length===0} onClick={send}>إرسال للعميل للموافقة</button></div></>}
 {!draft&&<><p className="notice">المقايسة المرسلة لا تُعدّل حفاظًا على النسخة التي شاهدها العميل.</p><button className="button" disabled={busy} onClick={create}>إنشاء إصدار جديد للتعديل</button></>}{msg&&<p style={{fontWeight:700,wordBreak:'break-word'}}>{msg}</p>}</div>}
