'use client';
import {useMemo,useState} from 'react';

type Bath={service:'new'|'replace'|'install_only';source:'ventic'|'customer';size:string;location:string;opening:boolean;electricity:boolean};
type Kitchen={fan:boolean;hood:boolean;external:boolean;hoodOwned:boolean;hoodType:string;hoodWidth:string;exit:string;opening:boolean;duct:number};
const bathPrice={new:350,replace:400,install_only:300};

export default function Order(){
 const [step,setStep]=useState(1),[bathCount,setBathCount]=useState(1),[kitchenCount,setKitchenCount]=useState(1);
 const [baths,setBaths]=useState<Bath[]>([]),[kitchens,setKitchens]=useState<Kitchen[]>([]);
 const [customer,setCustomer]=useState({name:'',phone:'',governorate:'القاهرة',area:'',address:'',date:'',time:''});
 const [accepted,setAccepted]=useState(false),[created,setCreated]=useState(''),[saving,setSaving]=useState(false);
 const start=()=>{setBaths(Array.from({length:bathCount},()=>({service:'new',source:'ventic',size:'غير محدد',location:'حائط',opening:true,electricity:true})));setKitchens(Array.from({length:kitchenCount},()=>({fan:true,hood:false,external:false,hoodOwned:true,hoodType:'هرمي',hoodWidth:'60',exit:'منور',opening:true,duct:0})));setStep(2)};
 const estimate=useMemo(()=>baths.reduce((s,b)=>s+bathPrice[b.service],0)+kitchens.reduce((s,k)=>s+(k.fan?400:0)+(k.hood?500:0)+(k.external?500:0)+(k.duct*250),0),[baths,kitchens]);
 return <main className="order"><div className="brand center"><i>V</i> Ventic Pro</div><section className="panel orderPanel"><Progress step={step}/>{step===1?<><h1>هنركب في كام مكان؟</h1><p>حدد عدد الحمامات والمطابخ. كل مكان هيكون له تفاصيل وخدمات خاصة به.</p><Counter label="الحمامات" icon="🚿" value={bathCount} set={setBathCount}/><Counter label="المطابخ" icon="🍳" value={kitchenCount} set={setKitchenCount}/><div className="total">إجمالي الأماكن <b>{bathCount+kitchenCount}</b></div><button className="button full" disabled={bathCount+kitchenCount===0} onClick={start}>التالي: تفاصيل الأماكن ←</button></>:<><h1>تفاصيل أماكن التركيب</h1><p>كل مكان مستقل. تقدر تختار أكتر من خدمة للمطبخ الواحد.</p>{baths.map((b,i)=><BathCard key={i} n={i+1} value={b} onChange={v=>setBaths(x=>x.map((a,j)=>j===i?v:a))}/>)}{kitchens.map((k,i)=><KitchenCard key={i} n={i+1} value={k} onChange={v=>setKitchens(x=>x.map((a,j)=>j===i?v:a))}/>)}<Estimate value={estimate}/><div className="orderActions"><button className="ghostBtn" onClick={()=>setStep(1)}>رجوع</button><button className="button" onClick={()=>setStep(3)}>التالي: بيانات الطلب ←</button></div></>}
{step===3&&<><h1>بيانات العميل والعنوان والموعد</h1><div className="grid2"><Field label="الاسم"><input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></Field><Field label="رقم الموبايل"><input placeholder="01xxxxxxxxx" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></Field><Field label="المحافظة"><select value={customer.governorate} onChange={e=>setCustomer({...customer,governorate:e.target.value})}><option>القاهرة</option><option>الجيزة</option><option>القليوبية</option></select></Field><Field label="المنطقة"><input value={customer.area} onChange={e=>setCustomer({...customer,area:e.target.value})}/></Field></div><Field label="العنوان بالتفصيل"><input value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></Field><div className="grid2"><Field label="التاريخ المفضل"><input type="date" value={customer.date} onChange={e=>setCustomer({...customer,date:e.target.value})}/></Field><Field label="الفترة"><select value={customer.time} onChange={e=>setCustomer({...customer,time:e.target.value})}><option value="">اختر الفترة</option><option>10 ص - 1 م</option><option>1 م - 4 م</option><option>4 م - 7 م</option><option>7 م - 10 م</option></select></Field></div><Estimate value={estimate}/><div className="orderActions"><button className="ghostBtn" onClick={()=>setStep(2)}>رجوع</button><button className="button" onClick={()=>setStep(4)}>مراجعة الطلب ←</button></div></>}
{step===4&&<><h1>مراجعة وتأكيد الطلب</h1><div className="review"><p><b>{customer.name||'الاسم غير مكتمل'}</b> — {customer.phone}</p><p>{customer.governorate}، {customer.area}، {customer.address}</p><p>الموعد: {customer.date} — {customer.time}</p><p>{baths.length} حمام + {kitchens.length} مطبخ</p></div><Estimate value={estimate}/><label className="consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>أفهم أن السعر المعروض تقديري وسيتم تأكيد السعر النهائي قبل تنفيذ التركيب.</span></label>{created&&<div className="successBox">✓ تم إنشاء الطلب — رقم الطلب <b>{created}</b></div>}<div className="orderActions"><button className="ghostBtn" onClick={()=>setStep(3)}>رجوع</button><button className="button" disabled={!accepted||!customer.name||!/^01\d{9}$/.test(customer.phone)||!customer.address||!customer.date||!customer.time} onClick={async()=>{setSaving(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,baths,kitchens,estimatedTotal:estimate})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر إنشاء الطلب');setCreated(d.orderNo)}catch(e){alert(e instanceof Error?e.message:'تعذر إنشاء الطلب')}finally{setSaving(false)}}}>{saving?'جاري الحفظ...':'تأكيد الطلب'}</button></div></>}<small>السعر المعروض تقديري وليس السعر النهائي. يتم تأكيد التكلفة بعد مراجعة الصور ومعلومات مكان التركيب.</small></section></main>
}
function Progress({step}:{step:number}){return <div className="progress"><span>الخطوة {step} من 4</span><div><b style={{width:`${step/4*100}%`}}/></div></div>}
function Counter({label,icon,value,set}:{label:string,icon:string,value:number,set:(v:number)=>void}){return <div className="counter"><span>{icon} <b>{label}</b></span><div><button onClick={()=>set(Math.max(0,value-1))}>−</button><strong>{value}</strong><button onClick={()=>set(Math.min(10,value+1))}>+</button></div></div>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Toggle({label,on,set}:{label:string,on:boolean,set:(v:boolean)=>void}){return <button type="button" className={'choice '+(on?'selected':'')} onClick={()=>set(!on)}>{on?'✓ ':''}{label}</button>}
function BathCard({n,value:v,onChange}:{n:number,value:Bath,onChange:(v:Bath)=>void}){return <article className="spaceCard"><h2>🚿 حمام {n}</h2><Field label="نوع الخدمة"><select value={v.service} onChange={e=>onChange({...v,service:e.target.value as Bath['service']})}><option value="new">تركيب بلاور جديد</option><option value="replace">استبدال بلاور قديم</option><option value="install_only">تركيب بلاور موجود عند العميل</option></select></Field><div className="grid2"><Field label="مصدر البلاور"><select value={v.source} onChange={e=>onChange({...v,source:e.target.value as Bath['source']})}><option value="ventic">شراء من Ventic Pro</option><option value="customer">موجود عند العميل</option></select></Field><Field label="مكان التركيب"><select value={v.location} onChange={e=>onChange({...v,location:e.target.value})}><option>حائط</option><option>شباك</option><option>سقف</option></select></Field><Field label="مقاس البلاور"><select value={v.size} onChange={e=>onChange({...v,size:e.target.value})}><option>غير محدد</option><option>15 سم</option><option>20 سم</option><option>25 سم</option><option>30 سم</option></select></Field></div><div className="choices"><Toggle label="فتحة الطرد جاهزة" on={v.opening} set={x=>onChange({...v,opening:x})}/><Toggle label="الكهرباء جاهزة" on={v.electricity} set={x=>onChange({...v,electricity:x})}/></div><label className="upload">📷 صور مكان التركيب <input type="file" accept="image/*" multiple/></label></article>}
function KitchenCard({n,value:v,onChange}:{n:number,value:Kitchen,onChange:(v:Kitchen)=>void}){return <article className="spaceCard"><h2>🍳 مطبخ {n}</h2><span className="subLabel">الخدمات المطلوبة</span><div className="choices"><Toggle label="بلاور تهوية" on={v.fan} set={x=>onChange({...v,fan:x})}/><Toggle label="تركيب هود" on={v.hood} set={x=>onChange({...v,hood:x})}/><Toggle label="مروحة طرد خارجية" on={v.external} set={x=>onChange({...v,external:x})}/></div>{v.hood&&<div className="grid2"><Field label="نوع الهود"><select value={v.hoodType} onChange={e=>onChange({...v,hoodType:e.target.value})}><option>هرمي</option><option>مسطح</option><option>بلت إن</option><option>Island</option><option>غير متأكد</option></select></Field><Field label="عرض الهود"><select value={v.hoodWidth} onChange={e=>onChange({...v,hoodWidth:e.target.value})}><option>60</option><option>70</option><option>90</option><option>مقاس آخر</option></select></Field></div>}<div className="grid2"><Field label="مكان خروج الهواء"><select value={v.exit} onChange={e=>onChange({...v,exit:e.target.value})}><option>منور</option><option>واجهة</option><option>شباك</option><option>سقف</option><option>غير متأكد</option></select></Field><Field label="طول خط الطرد التقريبي بالمتر"><input type="number" min="0" step="0.5" value={v.duct} onChange={e=>onChange({...v,duct:Math.max(0,Number(e.target.value))})}/></Field></div><div className="choices"><Toggle label="فتحة الطرد جاهزة" on={v.opening} set={x=>onChange({...v,opening:x})}/></div><label className="upload">📷 صور الحائط والهود ومخرج الطرد <input type="file" accept="image/*" multiple/></label></article>}
function Estimate({value}:{value:number}){return <div className="estimate"><span>التكلفة التقديرية الحالية</span><strong>{value.toLocaleString('ar-EG')} جنيه</strong><small>قد تضاف تكلفة فتحات، كهرباء، وصلات أو خامات بعد مراجعة الصور.</small></div>}
